// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqLDy6Z37zRDtRe5irPUXQMRNUbt9IUfU',
    appId: '1:356282770143:web:4f59a93a41e12401f0ff6a',
    messagingSenderId: '356282770143',
    projectId: 'presence-8e806',
    authDomain: 'presence-8e806.firebaseapp.com',
    storageBucket: 'presence-8e806.appspot.com',
    measurementId: 'G-19E3B0F9RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCIBMcEMw4B4kOhruMItDVP4SZ5GHp5Ic',
    appId: '1:356282770143:android:252daf408cb0ef59f0ff6a',
    messagingSenderId: '356282770143',
    projectId: 'presence-8e806',
    storageBucket: 'presence-8e806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSOnGGcDsr-dgjcO6G7Aja6k0GQMLdQ6s',
    appId: '1:356282770143:ios:a968911e2c417dc9f0ff6a',
    messagingSenderId: '356282770143',
    projectId: 'presence-8e806',
    storageBucket: 'presence-8e806.appspot.com',
    iosClientId: '356282770143-89oue26os3ogjvavvks4djfttve9jv43.apps.googleusercontent.com',
    iosBundleId: 'com.example.presence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSOnGGcDsr-dgjcO6G7Aja6k0GQMLdQ6s',
    appId: '1:356282770143:ios:a968911e2c417dc9f0ff6a',
    messagingSenderId: '356282770143',
    projectId: 'presence-8e806',
    storageBucket: 'presence-8e806.appspot.com',
    iosClientId: '356282770143-89oue26os3ogjvavvks4djfttve9jv43.apps.googleusercontent.com',
    iosBundleId: 'com.example.presence',
  );
}
